version: '3.9'
services:
  alexwebsite:
    image: nodejs-alex:latest
    container_name: alexwebsite
    restart: on-failure:5
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.alex.rule=Host(`alex.webguardx.com`)"
      - "traefik.http.routers.alex.entrypoints=websecure"
      - "traefik.http.routers.alex.tls.certresolver=myresolver"      
      - "traefik.http.routers.alex.tls=true"
      - "traefik.http.routers.alex.middlewares=default@file"
      - "traefik.http.services.alex.loadbalancer.server.port=3000"

networks:
  traefik_web:
    external: true
