name: Build Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Stop and remove previous container
        run: |
          PREVIOUS_CONTAINER=$(docker ps -aqf "ancestor=nodejs-alex:latest")
          if [ -n "$PREVIOUS_CONTAINER" ]; then
            docker stop "$PREVIOUS_CONTAINER"
            docker rm "$PREVIOUS_CONTAINER"
          fi

      - name: Build and tag the new Docker image
        run: |
          docker build . --file Dockerfile --tag nodejs-alex:new
          docker tag nodejs-alex:new nodejs-alex:latest

      - name: Run Docker container
        run: docker run --restart=on-failure:5 -d  nodejs-alex:latest --name alexwebsite --network="traefik_web" --label traefik.enable=true --label traefik.docker.network=treafik_web --label traefik.http.routers.alexweb.entrypoints=websecure --label traefik.http.routers.alexweb.rule=Host\(\`alex.ezshaping.pw\`\) --label traefik.http.services.alexweb.loadbalancer.server.port=80
