name: Build Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Stop and remove previous container
        run: |
          PREVIOUS_CONTAINER=$(docker ps -aqf "ancestor=nodejs-alex:latest")
          if [ -n "$PREVIOUS_CONTAINER" ]; then
            docker stop "$PREVIOUS_CONTAINER"
            docker rm "$PREVIOUS_CONTAINER"
          fi

      - name: Build and tag the new Docker image
        run: |
          docker build . --file Dockerfile --tag nodejs-alex:new
          docker tag nodejs-alex:new nodejs-alex:latest

      - name: Run Docker container
        run: docker run --restart=on-failure:5 -d -p 8081:3000/tcp nodejs-alex:latest
